[book]
authors = ["Le Quang Thang"]
language = "en"
multilingual = false
src = ""                     # Root of repo
title = "DevOps Book"

[preprocessor.alerts]

[preprocessor.mermaid]
command = "mdbook-mermaid"

[output.html]
additional-css = ["./theme/css/catppuccin.css"]
default-theme = "latte"
preferred-dark-theme = "macchiato"

smart-punctuation = true

site-url = "/devops-book/"
git-repository-url = "https://github.com/lethang7794/devops-book"
edit-url-template = "https://github.com/lethang7794/devops-book/edit/master{path}"

additional-js = [
  ".mdbook/mermaid/mermaid.min.js",
  ".mdbook/mermaid/mermaid-init.js",
]
